# Generated by Django 3.1.5 on 2021-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
